const popularFoodData = [
  {
    id: "1",
    title: "BLT Chicken Salad",
    img: "/images/chicken-salad.jpg",
    PreparetionTime: [
      "💼 Prep Time: 20 mins | 🥙 Cook Time: 30 mins ",
      "🍗 Servings: 2 | 🔥 Calories: ~400 per serving",
    ],
    ingredients: [
      "6 slices thick-cut bacon",
      "3 boneless, skinless chicken breasts (about 1.5 lbs)",
      "4 cups fresh romaine lettuce",
      "Tomatoes, ripe",
      "2 tbsp freshly squeezed lemon juice",
      "1/2 cup mayonnaise",
      "Salt and pepper",
    ],
  },
  {
    id: "2",
    title: "Spicy Chicken Wraps",
    img: "/images/spicy-chicken-wrap.jpg",
    PreparetionTime: [
      "💼 Prep Time: 15 mins | 🌯 Cook Time: 30 mins ",
      "🍗 Servings: 4 | 🔥 Calories: ~350 per serving",
    ],
    ingredients: [
      "4 boneless, skinless chicken thighs",
      "2–4 tortilla wraps or paratha breads",
      "Olive oil, for frying",
      "2 spring onions, finely shredded 🧅",
      "¼ head of pointed cabbage, shredded",
    ],
  },
  {
    id: "3",
    title: "Crispy French Fries",
    img: "/images/french fries.jpg",
    PreparetionTime: [
      "💼 Prep Time: 15 mins | 🍟 Cook Time: 30 mins ",
      "🍗 Servings: 2 | 🔥 Calories: ~500 per serving",
    ],
    ingredients: [
      "2 large potatoes, cut into fries",
      "1 tbsp olive oil",
      "½ tsp salt & black pepper",
      "½ tsp garlic powder",
      "¼ cup grated Parmesan 🧀",
      "1 tbsp fresh parsley, chopped",
      "Garlic aioli or truffle mayo for dipping",
    ],
  },
  {
    id: "4",
    title: "Pizza Burgers",
    img: "/images/pizza burger.jpg",
    PreparetionTime: [
      "💼 Prep Time: 35 mins | 🍔 Cook Time: 30 mins ",
      "🍗 Servings: 1| 🔥 Calories: ~400 per serving",
    ],
    ingredients: [
      "1 pound ground beef",
      "16-24 slices pepperoni",
      "½ cup pizza sauce",
      "1 teaspoon Italian seasoning",
      "½ teaspoon garlic powder",
      "½ teaspoon salt",
      "¼ teaspoon black pepper",
      "4 hamburger buns, split and toasted",
      "1 cup shredded mozzarella cheese",
    ],
  },
  {
    id: "5",
    title: "Grilled Salmon",
    img: "/images/grilledsalmon.jpg",
    PreparetionTime: [
      "💼 Prep Time: 10 mins | 🍱 Cook Time: 15 mins",
      "🐟 Servings: 2 | 🔥 Calories: ~420 per serving",
    ],
    ingredients: [
      "2 salmon fillets",
      "1 tbsp olive oil",
      "1 lemon (sliced)",
      "1 tsp garlic powder",
      "Fresh dill",
      "Salt and black pepper",
    ],
  },
  {
    id: "6",
    title: "Spaghetti Carbonara",
    img: "/images/carabona.jpg",
    PreparetionTime: [
      "💼 Prep Time: 20 mins | 🍝 Cook Time: 15 mins",
      "🍽️ Servings: 3 | 🔥 Calories: ~500 per serving",
    ],
    ingredients: [
      "Spaghetti pasta",
      "4 eggs",
      "Parmesan cheese, grated",
      "Black pepper, freshly ground",
      "6 strips bacon or pancetta",
      "1 tbsp olive oil",
      "Salt to taste",
    ],
  },
  {
    id: "7",
    title: "Beef Tacos",
    img: "/images/tacos.jpg",
    PreparetionTime: [
      "💼 Prep Time: 20 mins | 🌮 Cook Time: 10 mins",
      "🍖 Servings: 4 | 🔥 Calories: ~380 per serving",
    ],
    ingredients: [
      "Tortillas (8 pieces)",
      "1 lb ground beef",
      "1 onion, chopped",
      "1 tomato, diced",
      "Cheddar cheese, shredded",
      "Lettuce, chopped",
      "Salsa",
    ],
  },
  {
    id: "8",
    title: "Vegetable Stir Fry",
    img: "/images/stir-fry.jpg",
    PreparetionTime: [
      "💼 Prep Time: 15 mins | 🍲 Cook Time: 10 mins",
      "🥦 Servings: 2 | 🔥 Calories: ~300 per serving",
    ],
    ingredients: [
      "Broccoli florets",
      "Carrots, sliced",
      "Bell peppers, mixed colors",
      "Soy sauce, 3 tbsp",
      "Garlic, minced",
      "Sesame oil, 1 tbsp",
      "Cornstarch slurry (optional)",
    ],
  },
];
export default popularFoodData;
